### ISSUE TITLE
Vaani Listens from the moment it is started

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/vaani#19]
The red circle indicating "listening" is on from the moment Vaani is started

![vaani](https://cloud.githubusercontent.com/assets/12054740/8722228/9c851c60-2bc2-11e5-8928-b065e9450dc0.png)

**Comment by jedireza** [comment]
Yes I noticed this too. When the app starts I get access to the mic and setup the events to listen to the volume levels (for the listening motion). I can try changing it if you see it as a problem.

Won't this be the case if we have word spotting anyways, since the mic will be active all the time?

**Comment by kdavis-mozilla** [comment]
You're right about the word spotting case. I guess it will be on anyway. Stupidly,
I hadn't thought that through.

Ultimately, I'm worried about the appearance that we are listening in despite the
fact that we aren't.

**Comment by andrenatal** [comment]
This is by design, since the API uses getusermedia to receive record the voice. There is nothing we can do to change this on Gaia. If you wish to change this, need to ask in #media channel.

**Comment by kdavis-mozilla** [comment]
When word spotting is integrated, then yes the indicator should always be on and there is nothing
we can or should do about it.

However, word spotting is currently not integrated.

So, we shouldn't be listening all the time, we should only listen when the user requests we listen.

**Comment by jedireza** [comment]
Maybe I could try to change it and use `getusermedia` only when we're listening to a command. If we notice a performance degradation or another negative side affect by doing that, we can always move back to the current setup since we know it works.

**Comment by andrenatal** [comment]
This  don`t have anything to do with wordspot. It is a getusermedia beahviour, and even if we don't pass a DomMediaStream to the constructor, gum will be called internally in Gecko [1], showing the red icon on top. Again, there is nothing to do to fix this on Gaia neither on the app, but yes on Gecko. So this is not an issue here, but an expected behavior.

[1] https://github.com/mozilla/gecko-dev/blob/master/dom/media/webspeech/recognition/SpeechRecognition.cpp#L732

**Comment by kdavis-mozilla** [comment]
@jedireza I think that sounds reasonable.

We don't want to give the user the impression that we are in any way spying on them.

**Comment by andrenatal** [comment]
@jedireza Even if you don't call gum in js, will be called internally. 

https://github.com/mozilla/gecko-dev/blob/master/dom/media/webspeech/recognition/SpeechRecognition.cpp#L732

**Comment by andrenatal** [comment]
@jedireza  I just tested on my phone, and after ~30 secs without activity, the red icon disappears, and when I push the mic button again, recording icon appears but don't listen anything.

**Comment by kdavis-mozilla** [comment]
@andrenatal Can you re-open this issue?

**Comment by andrenatal** [comment]
@kdavis-mozilla ok, but I am not sure if this issue belongs here.

**Comment by kdavis-mozilla** [comment]
@andrenatal I was wondering about where to track Vaani issues too, and right now this seems about as good a place as any. I think when Vaani's in Gaia, we can move over to Bugzilla.

**Comment by andrenatal** [comment]
@kdavis-mozilla I agree, but being specific about the matter of this issue, looks more related to gum than Gaia/Vaani itself.

**Comment by kdavis-mozilla** [comment]
@andrenatal I agree. Once we start listening the indicator is on and that's out of our hands, as it should be.

All I am saying is that we should only start listening when the user asks us to. That way we don't give the impression that we are spying in on the user.

The issue I am concerned with is not really, at its core, technical, but it's one of user perception.

**Comment by andrenatal** [comment]
You are correct. My phone is still with the rec icon on! One hour after!

**Comment by jedireza** [comment]
`getusermedia`/`attachmediastream` don't seem to have good mechanics to "release user media" and "detach media stream". I'll leave this issue open so we can try to resolve later.
