### ISSUE TITLE
Vaani is trying to use a ungrammatical grammar

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/vaani#42]
See [bug 1197455 comment 6](https://bugzilla.mozilla.org/show_bug.cgi?id=1197455#c6) and the associated discussion

**Comment by andrenatal** [comment]
Thanks for that @kdavis-mozilla . Should we keep this open? We have a lof of cases generating the grammar that can lead to this, that's maybe better keep it open for tracking...

**Comment by andrenatal** [comment]
@kdavis-mozilla can we close this?

**Comment by kdavis-mozilla** [comment]
[Bug 1197455](https://bugzilla.mozilla.org/show_bug.cgi?id=1197455) only made it so the the backend did not crash when passed an invalid grammar. The frontend must still be made to not produce an invalid grammar. So, I'd say we keep this open.
