### ISSUE TITLE
Dynamic grammar includes words that are only punctuation

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/vaani#55]
Flashed current gecko and gaia onto a flame device and installed Vaani. Part of the grammar produced included the "word" "-". In other words, it included a "-" separated from other words by spaces.

This caused the g2p algorithm to crash Bug 1202989, which I am fixing now.

But the question really is: What should be done if an app, for example, is called "Ready - Set - Go"?

**Comment by kdavis-mozilla** [comment]
For example, looking at the apps installed there is an app named "UI tests - Privileged App", and there are likely other similar problems with other app names.

**Comment by jedireza** [comment]
I'd like to see the recognition engine handle this internally. Could we make it so special characters are treated like white space? Essentially just ignoring things/characters that aren't spoken.

**Comment by andrenatal** [comment]
Thanks for that @kdavis-mozilla . Should we keep this open? We have a lot of cases generating the grammar that can lead to this situation that maybe is better keep it open for tracking...

**Comment by andrenatal** [comment]
@jedireza the engine should handle wrong chars and

**Comment by andrenatal** [comment]
@jedireza the engine should handle these chars and prevent crashing but should not arbitrarily change parts of the grammar that is passed via the api. So I afraid we'll need to replace these chars and do a basic cleaning on the generation.
