### ISSUE TITLE
White screen (ffxos latest nightly)

### ISSUE THREAD

**Issue by Hywan** [mozilla/vaani#66]
Hello :-),

I did clone the repository and installed Vaani with WebIDE (packaged app > `src/`, hop). When starting the application, I have a white screen.

Any idea why?

Thanks!

**Comment by jedireza** [comment]
Thanks for creating an issue.

I just did a fresh clone of the repo and followed the instructions in the README. I don't get a white screen and at a quick glance, things seem to be working as expected.

---

### Setup

``` bash
$ git clone git@github.com:mozilla/vaani.git
$ cd vaani
$ npm run setup
```

### Build

``` bash
$ npm run build
```

### Flash

Once built you can flash the `./build` directory to your device using WebIDE.

**Comment by Hywan** [comment]
It works. I have an issue with `node-gyp` build though, but this seems to not be related to this project. So, thanks!

**Comment by Hywan** [comment]
(and thanks for this awesome project :-])
